project:
  type: website
  output-dir: docs

website:
  title: "BW Tjepkes"
  site-url: https://btjepkes.github.io/
  repo-url: https://github.com/btjepkes/btjepkes.github.io
  description: "A professional portfolio and technical blog for Benjamin Tjepkes."
  favicon: assets/logo-1.png
  page-navigation: true
  back-to-top-navigation: false
  search:
    location: sidebar
    type: textbox
  open-graph: true
  twitter-card:
    creator: "@BTjepkes"
    title: "Portfolio | B.W. Tjepkes"
  cookie-consent:
    type: implied
    style: interstitial
    palette: light
    prefs-text: "User Cookies ðŸª Preferences"
  google-analytics: 
    tracking-id: "G-ESKNL9H1KZ"
    version: 4
  navbar:
    pinned: true
    logo: assets/site-logo-green.png
    left:
      - icon: linkedin
        text: "LinkedIn"
        href: https://www.linkedin.com/in/benjamintjepkes/
        aria-label: LinkedIn Profile
      - icon: github
        text: "Code"
        href: https://github.com/btjepkes
        aria-label: GitHub Profile
      - icon: twitter
        text: "Tweets"
        href: https://twitter.com/BTjepkes
        aria-label: Twitter Profile
     
    right:
        - icon: house
          href: index.html
        - sidebar:overview
        - sidebar:works
        - sidebar:resources

  sidebar:
    - id: overview
      title: "Overview"
      style: "floating"
      background: "#e8e8e8"
      collapse-level: 2
      contents: 
        - href: about/index.qmd
        - href: curriculum-vitae/index.qmd
        - href: contact.qmd
    - id: works
      title: "Projects"
      contents:
        - posts/index.qmd
        - gallery/index.qmd
        - research/index.qmd
    - id: resources
      title: "Resources"
      contents:
        - resources/index.qmd

  page-footer:
    center: >-
      Made with [Quarto](https://quarto.org/) and [RStudio](https://posit.co/products/open-source/rstudio/) | License: [CC BY-NC](https://creativecommons.org/licenses/by-nc/4.0/)
    left:
      - text: "&copy; Copyright 2021-2023 - B.W. Tjepkes"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/benjamintjepkes/
        aria-label: LinkedIn Profile
      - icon: github
        href: https://github.com/btjepkes
        aria-label: GitHub Profile
      - icon: twitter
        href: https://twitter.com/BTjepkes
        aria-label: Twitter Profile
      - icon: house-fill
        href: index.html
        aria-label: home page
        
execute:
  freeze: true

format:
  html:
    author:
      - name: Benjamin Tjepkes  
        url: //about/index.qmd
        orcid: 0009-0002-5524-2675
    template-partials: 
      - title-block.html
    theme: custom.scss
    abstract-title: "What Is This About?"
    toc: true
    toc-title: "On This Page:"
    smooth-scroll: true
    number-sections: false
    pagetitle: "{{< meta title >}} | B.W. Tjepkes"
    title-block-banner: true
    title-block-categories: false
    anchor-sections: false
    highlight-style: github
    link-external-newwindow: true
    code-link: true
    code-overflow: scroll
    grid:
      sidebar-width: 250px
      body-width: 900px
      gutter-width: 30px
    filters: 
      - lightbox
    lightbox: auto
    
    